---
include:
  - board: nrf52840dongle
    shield: settings_reset

  - board: nice_nano
    shield: settings_reset

  - board: nrf52840dongle
    shield: eyelash_sofle_dongle
    artifact-name: eyelash_sofle_dongle

  - board: nice_nano
    shield: eyelash_sofle_left
    artifact-name: eyelash_sofle_left

  - board: nice_nano
    shield: eyelash_sofle_right
    artifact-name: eyelash_sofle_right
